# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "TheZombieTheme"
license = "MIT"
min_version = 0.14

[author]
  name = "Fernando Moro Hern√°ndez"
  homepage = "www.procesozombie.com"
